services:
  mass-flasher:
    build:
      context: ..
      dockerfile: mass_flasher/Dockerfile
    container_name: mass_flasher_app
    privileged: true
    user: root
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ../controlboard:/app/controlboard_repo
      - repo_cache:/app/repo_cache
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  repo_cache:

